AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda function to read csv file content from a S3 bucket, manipulate records, and insert or update records to target DynamoDB tables.
Parameters:
    LambdaLayerParameter:
      Type: String
      Default: "arn:aws:lambda:us-east-1:909117335741:layer:iawa-layer:2"
    S3BucketName:
      Type: String
    APPIMGROOTPATH:
      Type: String
    BibliographicCitation:
      Type: String
    CollectionCategory:
      Type: String
    DYNOCollectionTABLE:
      Type: String
    DYNOArchiveTABLE:
      Type: String
    NOIDNAA:
      Type: String
      Default: "53696"
    NOIDScheme:
      Type: String
      Default: "ark:/"
    NOIDTemplate:
      Type: String
      Default: "eeddeede"
    REGION:
      Type: String
      Default: "us-east-1"
    RightsHolder:
      Type: String
    RightsStatement:
      Type: String
    LongURLPath:
      Type: String
    ShortURLPath:
      Type: String
    APIKey:
      Type: String
    APIEndpoint:
      Type: String
Resources:
  s3toddb:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref LambdaLayerParameter
      Runtime: python3.7
      CodeUri: .
      Description: An AWS Lambda function to read csv file content from a S3 bucket, manipulate records, and insert or update records to target DynamoDB tables.
      MemorySize: 2048
      Timeout: 300
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DYNOCollectionTABLE
        - DynamoDBCrudPolicy:
            TableName: !Ref DYNOArchiveTABLE
        - S3ReadPolicy:
            BucketName: !Ref S3BucketName
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceS3Bucket
            Events:
              - 's3:ObjectCreated:*'
      Environment:
        Variables:
          DEBUG: 1
          APP_IMG_ROOT_PATH: !Ref APPIMGROOTPATH
          Bibliographic_Citation: !Ref BibliographicCitation
          Collection_Category: !Ref CollectionCategory
          DYNO_Collection_TABLE: !Ref DYNOCollectionTABLE
          DYNO_Archive_TABLE: !Ref DYNOArchiveTABLE
          NOID_NAA: !Ref NOIDNAA
          NOID_Scheme: !Ref NOIDScheme
          REGION: !Ref REGION
          Rights_Holder: !Ref RightsHolder
          Rights_Statement: !Ref RightsStatement
          LONG_URL_PATH: !Ref LongURLPath
          SHORT_URL_PATH: !Ref ShortURLPath
          API_KEY: !Ref APIKey
          API_ENDPOINT: !Ref APIEndpoint
  SourceS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  s3toddbFunction:
    Description: "s3toddb Lambda Function ARN"
    Value: !GetAtt s3toddb.Arn
  s3toddbFunctionName:
    Description: "s3toddb Lambda Function name"
    Value: !Ref s3toddb
  s3toddbIamRole:
    Description: "Implicit IAM Role created for Noid function"
    Value: !GetAtt s3toddbRole.Arn
  s3toddbBucket:
    Description: "s3toddbBucket Bucket name"
    Value: !Ref S3BucketName